// ─── OTLP wire format (incoming JSON payload) ────────────────────────────────

export interface OtlpAttributeValue {
  stringValue?: string;
  intValue?: string;
  doubleValue?: number;
  boolValue?: boolean;
  arrayValue?: { values: OtlpAttributeValue[] };
}

export interface OtlpAttribute {
  key: string;
  value: OtlpAttributeValue;
}

export interface OtlpSpan {
  traceId: string;
  spanId: string;
  parentSpanId?: string;
  name: string;
  kind: number;
  startTimeUnixNano: string;
  endTimeUnixNano: string;
  attributes?: OtlpAttribute[];
  status?: { code: number; message?: string };
}

export interface OtlpPayload {
  resourceSpans?: Array<{
    resource?: { attributes?: OtlpAttribute[] };
    scopeSpans?: Array<{
      scope?: { name?: string; version?: string };
      spans?: OtlpSpan[];
    }>;
  }>;
}

// ─── Parsed (internal) types — output of otlp-parser ─────────────────────────

export type SpanKind = 'CHAIN' | 'EMBEDDING' | 'RETRIEVER' | 'RERANKER' | 'LLM' | 'SPAN';

export interface RetrievalDocument {
  id: string;
  score: number;
  content?: string;
}

export interface ParsedSpan {
  traceId: string;
  spanId: string;
  parentSpanId?: string;
  name: string;
  kind: SpanKind;
  startTimeMs: number;
  endTimeMs: number;
  latencyMs: number;
  operationName?: string;
  model?: string;
  system?: string;
  inputTokens?: number;
  outputTokens?: number;
  rawAttributes: string; // JSON string of original OtlpAttribute[]
  documents?: RetrievalDocument[];
  prompt?: string; // ai.prompt or gen_ai.prompt for context assembly
}

export interface ParsedTrace {
  traceId: string;
  serviceName: string;
  spans: ParsedSpan[];
}

// ─── DB row shapes (returned to frontend via tRPC) ────────────────────────────

export interface RagTrace {
  id: string; // = traceId
  serviceName: string;
  query: string | null;
  source: 'traceai' | 'langfuse' | 'vercel' | 'manual';
  totalLatencyMs: number | null;
  spanCount: number;
  chunkCount: number;
  createdAt: number; // unix ms
}

export interface RagSpan {
  id: string; // = spanId
  traceId: string;
  parentSpanId: string | null;
  name: string;
  kind: SpanKind;
  startTimeMs: number;
  endTimeMs: number;
  latencyMs: number;
  operationName: string | null;
  model: string | null;
  system: string | null;
  inputTokens: number | null;
  outputTokens: number | null;
}

export interface RagChunk {
  id: string; // UUID generated by RAGScope
  spanId: string;
  traceId: string;
  chunkId: string; // from gen_ai.retrieval.documents[].id
  content: string | null;
  scoreRaw: number | null;
  scoreNormalized: number | null;
  rankRetrieval: number | null;
  rankReranked: number | null;
  scoreReranked: number | null;
  tokenCount: number | null;
  vectorStore: string | null;
  inContext: boolean;
  contextPosition: number | null;
  overlapWithNext: number | null;
  scoreMissing: boolean; // true when source=langfuse and no score logged
}
